### ISSUE TITLE
object 'QuantizedLinear' has no attribute 'quantize_module´

### ISSUE THREAD

**Issue by CBaquero** [ml-explore/mlx-examples#704]
I was using a prior version of MLX, probably version .10, and was able to run:

model, tokenizer = load("mlx-community/Meta-Llama-3-8B-Instruct-4bit")

Now after upgrading to MLX version .11 I get the error:

--
nn.QuantizedLinear.quantize_module(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QuantizedLinear' has no attribute 'quantize_module'
--

This functionality was described in https://ml-explore.github.io/mlx/build/html/python/nn/_autosummary/mlx.nn.QuantizedLinear.html

And now seems to be missing.

**Comment by awni** [comment]
Yes that changed. You can upgrade MLX LM and it should be fixed `pip install -U mlx-lm`.

**Comment by LucaKoval** [comment]
I'm still getting the described error when running `python convert.py --hf-path mistralai/Mistral-7B-v0.1 -q` from the `lora` example folder.

**Comment by awni** [comment]
Sorry about that, fix in #708, once that lands you can pull the latest repo and it should work.

**Comment by LucaKoval** [comment]
Thank you so much! Works perfectly now.
